# Generated by Django 3.2.25 on 2024-04-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='public',
            new_name='my_public',
        ),
    ]
