# Generated by Django 3.2.25 on 2024-04-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_public_products_my_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='my_public',
            new_name='public',
        ),
    ]
